#!/usr/bin/env bash
# Sanitized StructAgent A2A sender template.
# Requires:
#   STRUCTAGENT_A2A_URL   e.g. http://127.0.0.1:18800
#   STRUCTAGENT_A2A_TOKEN generated by your own gateway

set -euo pipefail

A2A_URL="${STRUCTAGENT_A2A_URL:-http://127.0.0.1:18800}"
A2A_TOKEN="${STRUCTAGENT_A2A_TOKEN:?Set STRUCTAGENT_A2A_TOKEN}"
AGENT_ID=""
MESSAGE=""
TIMEOUT="${STRUCTAGENT_A2A_TIMEOUT:-180}"

usage() {
  echo "Usage: $0 --to <agent_id> --message <text>" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --to) AGENT_ID="$2"; shift 2 ;;
    --message) MESSAGE="$2"; shift 2 ;;
    --timeout) TIMEOUT="$2"; shift 2 ;;
    *) usage ;;
  esac
done

[[ -n "$AGENT_ID" && -n "$MESSAGE" ]] || usage

MSG_ID="structagent-$(date +%s)-$$"
PAYLOAD=$(python3 - "$MSG_ID" "$AGENT_ID" "$MESSAGE" <<'PY'
import json, sys
msg_id, agent_id, text = sys.argv[1:4]
print(json.dumps({
  "jsonrpc": "2.0",
  "method": "message/send",
  "id": msg_id,
  "params": {
    "message": {
      "role": "user",
      "messageId": msg_id,
      "agentId": agent_id,
      "parts": [{"type": "text", "text": text}]
    }
  }
}))
PY
)

curl -sf --max-time "$TIMEOUT" \
  -X POST "$A2A_URL/a2a/jsonrpc" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $A2A_TOKEN" \
  -d "$PAYLOAD"
